pipeline:
  name: Build rh_wbcode
  identifier: Build_rh_wbcode_1759177747442
  projectIdentifier: rh_sm_infra
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: |
                      echo "Welcome to Harness CI"
                      echo "Build Type: <+codebase.build.type>"
                      if [ "<+codebase.build.type>" = "PR" ]; then
                        echo "PR Number: <+codebase.prNumber>"
                      else
                        echo "Branch: <+codebase.branch>"
                      fi
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
    - stage:
        name: Code Quality
        identifier: Code_Quality
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: SonarQube Scan
                  identifier: SonarQube_Scan
                  spec:
                    shell: Bash
                    envVariables:
                      SONAR_PROJECT_KEY: <+variable.SONAR_PROJECT_KEY>
                      SONAR_ORGANIZATION: <+variable.SONAR_ORGANIZATION>
                      SONAR_HOST_URL: <+variable.SONAR_HOST_URL>
                      SONAR_TOKEN: <+secrets.getValue("SONAR_TOKEN")>
                    command: |
                      # Install SonarScanner
                      export SONAR_SCANNER_VERSION=7.2.0.5079
                      export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux-x64
                      curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux-x64.zip
                      unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
                      export PATH=$SONAR_SCANNER_HOME/bin:$PATH
                      
                      # Run SonarQube scan
                      sonar-scanner \
                        -Dsonar.projectKey=$SONAR_PROJECT_KEY \
                        -Dsonar.organization=$SONAR_ORGANIZATION \
                        -Dsonar.sources=code \
                        -Dsonar.host.url=$SONAR_HOST_URL \
                        -Dsonar.token=$SONAR_TOKEN \
                        -Dsonar.exclusions=**/node_modules/**,**/target/**,**/*.test.js,**/*.spec.js
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: org.svktekninjas
        repoName: rh_wbcode
        build: <+input>
